name: Run Ansible on EKS nodes

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y ansible python3-boto3 python3-botocore python3-venv unzip curl

          # Install AWS Session Manager Plugin (required for SSM connection)
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
          sudo dpkg -i session-manager-plugin.deb
          session-manager-plugin --version

          # Create and activate a virtual environment for Ansible
          python3 -m venv ~/ansible-venv
          source ~/ansible-venv/bin/activate

          pip install --upgrade pip
          pip install boto3 botocore ansible
          ansible-galaxy collection install amazon.aws

      - name: Test dynamic inventory
        run: |
          source ~/ansible-venv/bin/activate
          ansible-inventory -i aws_ec2.yaml --list -v

      - name: Run Ansible playbook
        run: |
          export PATH=$PATH:/usr/local/bin
          ~/ansible-venv/bin/ansible-playbook -i aws_ec2.yaml ansible_check.yaml
